### PR TITLE
Added advancing button, also added compatibility to run ...

### PR DESCRIPTION
**Pull request by mofosyne**
... on android studio. Btw, there is not very much comments, it wasn't instant to pinpoint what is exactly going on.

Do you have the latest grade version? My android studio had to modify something in gradle to make it run.

Oh btw my email is mofosyne @ gmail . com
so just send me a quick email, and we can talk about ways to extend this. Oh, and btw I got a google marketplace account, so if you want me to upload this to google marketplace I can do it.

Oh, and in terms of adding instructions for users to read. Does this approach floats your boat? https://github.com/mofosyne/NFCMessageBoard#for-android-coders basically the readme is synced from github and the readme in the app.

### CODE REVIEW

**Comment by xloem** [comment]
Nice!

Would it be possible to split each change (gradle, android-studio, next button) into a separate commit or pull request?

Could you split the button text out into a string resource so that svetlemodry can translate it to Czech?

Thanks for the comment feedback.  I'm glad to answer specific questions about the code here or via email (my email is listed in the commit log).  Feel free to add commenting as you understand the code.

I'm using a very old version of android-studio.  I'll upgrade.

The wiki might be a good place for design work and some discussion, too.

I've thought the application is not user-friendly enough yet to put on google.  But feel free to if you think it's a good idea.  I'd wait until it we've gotten it to behave nicely enough that people will enjoy it and feel it meets their expectations.

The readme / instruction approach sounds great.  There'd need to be a UI to access it, of course.  It might be confusing to a future developer who tries to change the file in the project and discovers their changes erased -- there might be an even better solution.

**Comment by mofosyne** [comment]
Ah, I'm not quite sure how to do that. But the only changes for the buttons, is a function added in the bottom of the send.java and it's corresponding activity. Not hard to reimplement.

I have no problems about holding off, if you think it's not yet ready.

And yea, feel free to lift my approach for syncing the readme file to the app's resource. It does mean that to change the readme in the app, you shouldn't touch the readme in the resource folder. Instead you need to change the readme in the github project root.

**Comment by xloem** [comment]
Only remaining issue: the button text is hidden when the phone is in landscape mode.

**Comment by xloem** [comment]
I've merged the changes so far into a new branch named 'advancebutton'

**Comment by xloem** [comment]
Fixes #15

**Pull request merged**
